User:
  user_path: /Users/patrick/desktop/Cinnamon AI/src/2020TWBootcamp/ZaiLaGan
Linebot:
  access_token: M0tb09mdq8bGe9X5nIEnxU6XaKTVSv/BnMcQ5VndMjrt6SbJXzxcCeu5Ke5hsbGl+Yks70NcLzQKHqKRZJNpO+DdNbjxXidcR21kSgsdf62Is18y16sOYCCwhJGiT8eGk+Ujg0/1+1RPegC4X2kpCAdB04t89/1O/w1cDnyilFU=
  secret: 6ebc8d1f30c6a9d6de041e8a59a5cff2
Model:
  bert_wwm_ext_chinese: hfl/chinese-bert-wwm-ext
  bert_base_chinese: bert-base-chinese
  gpt2_chinese: models/gpt2_chinese/prose_wiki_novel_finetuned
  ner: utilities/NER/NER_data/data_path
Data:
  pinyin: data/spelling_error/pinyin.pkl
  stroke: data/spelling_error/stroke.pkl
  dictionary: data/word_dictionary/word_jieba.txt
  common_char_set: data/spelling_error/common_char_set.txt
  confusion: data/spelling_error/confusion.txt
  place: data/ner/place.txt
  person: data/ner/person.txt 
  ssc: data/ner/sound_shape_code